openapi: 3.0.0
info:
  title: 會員系統
  version: 1.0.0
servers:
  -
    url: api-member.sit.kkday.com
components:
  parameters:
    user-uuid:
      name: user-uuid
      in: header
      description: 操作人員
      required: true
      schema:
        type: string
    locale:
      name: locale
      in: header
      description: 語系
      required: true
      schema:
        type: string
  schemas:
    response:
      type: object
      properties:
        metadata:
          type: object
          properties:
            status: 
              type: string
              example: '0000'
            desc: 
              type: string
              example: '成功'
        data:
          type: object
paths:
  /api/v1/login/token-generate:
    post:
      tags:
        - Login/Token
      summary: 'Token - 產生login token'
      operationId: token_generate
      parameters:
        -
         $ref : '#/components/parameters/user-uuid'
        -
         $ref : '#/components/parameters/locale'
        -
          name: 'memberUuid'
          in: query
          description: 會員編號
          required: true
          schema:
            type: string
        -
          name: loginChannel
          in: query
          description: 登入的channel
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
              example:
                metadata: { status: '0000', desc: 產生成功 }
                data: { loginToken : 'fasfllmvldsfaldsjffdasdf'}
  /api/v1/login/token-validate:
    post:
      tags:
        - Login/Token
      summary: 'Token - 驗證login token'
      operationId: token_validate
      parameters:
        -
         $ref : '#/components/parameters/user-uuid'
        -
         $ref : '#/components/parameters/locale'
        -
          name: 'loginToken'
          in: query
          description: 登入token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
              example:
                metadata: { status: '0000', desc: 驗證成功 }
                data: { memberUuid : 'fasfllmvldsfaldsjffdasdf', channel : 'KKDAY_IN_APP'}