openapi: 3.0.0
info:
  title: 會員系統
  version: 1.0.0
servers:
  -
    url: api-member.sit.kkday.com
components:
  parameters:
    user-uuid:
      name: user-uuid
      in: header
      description: 操作人員
      required: true
      schema:
        type: string
    locale:
      name: locale
      in: header
      description: 語系
      required: true
      schema:
        type: string
  schemas:
    response:
      type: object
      properties:
        metadata:
          type: object
          properties:
            status: 
              type: string
              example: '0000'
            desc: 
              type: string
              example: 'success'
        data:
          type: object
paths:
  /api/v1/login/token-generate:
    post:
      tags:
        - Login/Token
      summary: 'Token - 產生login token'
      operationId: token_generate
      parameters:
        -
         $ref : '#/components/parameters/user-uuid'
        -
         $ref : '#/components/parameters/locale'
        -
          name: 'memberUuid'
          in: query
          description: 會員編號
          required: true
          schema:
            type: string
        -
          name: loginId
          in: query
          description: 登入取得的loginId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 產生token response，<br />錯誤類型有：<br />
            ML01：token cache save failed(token cache 儲存失敗)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
              example:
                成功範例:
                  metadata: { status: '0000', desc: 'success' }
                  data: { loginToken : 'fasfllmvldsfaldsjffdasdf'}
                錯誤ML01範例:
                  metadata: { status: 'ML01', desc: 'token cache save failed' }
                  data : {}
  /api/v1/login/token-validate:
    post:
      tags:
        - Login/Token
      summary: 'Token - 驗證login token'
      operationId: token_validate
      parameters:
        -
         $ref : '#/components/parameters/user-uuid'
        -
         $ref : '#/components/parameters/locale'
        -
          name: 'loginToken'
          in: formData
          description: 登入token
          required: true
          schema:
            type: string
            example: "fasfllmvldsfaldsjffdasdf"
      responses:
        '200':
          description: 驗證token response，<br />錯誤類型有：<br />
            ML02：token cache get failed(token cache 讀取失敗),<br />
            ML03：token validate failed(token 驗證失敗)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
              example:
                成功範例:
                  metadata: { status: '0000', desc: 'success' }
                  data: { memberUuid : 'fasfllmvldsfaldsjffdasdf', loginId : 'kk123@kkday.com'}
                錯誤ML02範例:
                  metadata: { status: 'ML02', desc: 'token cache get failed' }
                  data : {}
                錯誤ML03範例:
                  metadata: { status: 'ML03', desc: 'token validate failed' }
                  data : {}