openapi: 3.0.0
info:
  title: 會員系統
  contact:    
  version: 1.0.0
servers:
  -
    url: api-member.sit.kkday.com
paths:
  /api/v1/coupons/retain:
    post:
      tags:
        - coupon
      summary: 'Coupon - 領取 Retain'
      operationId: retain
      parameters:
        -
          name: user-uuid
          in: header
          description: 操作人員
          required: true
          schema:
            type: string
        -
          name: locale
          in: header
          description: 語系
          required: true
          schema:
            type: string
        -
          name: X-Api-Key
          in: header
          description: 驗證
          required: true
          schema:
            type: string
        -
          name: 'memberUuids[]'
          in: query
          description: 會員編號列表
          required: true
          schema:
            type: string
        -
          name: coupon
          in: query
          description: coupon
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                example:
                  metadata: { status: '0000', desc: 領取成功 }
                  data: { coupon: SGWATSONSW14I7, results: [{ memberUuid: aaaaaaaa-d5f8-4e16-a636-19000565bcb7, code: '0000', message: 領取成功 }, { memberUuid: bbbbbbbb-d5f8-4e16-a636-19000565bcb7, code: '0000', message: 領取成功 }] }
  
